using System.Drawing;

namespace RayMmdNodeEditor.Graph;

public static partial class NodeRegistry
{
    private static void AddMathDefinitions(Dictionary<NodeKind, NodeDefinition> definitions)
    {
        foreach (var pair in new Dictionary<NodeKind, NodeDefinition>
        {
            [NodeKind.Add] = new(
                NodeKind.Add,
                Title(NodeKind.Add),
                Description(NodeKind.Add),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Subtract] = new(
                NodeKind.Subtract,
                Title(NodeKind.Subtract),
                Description(NodeKind.Subtract),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Multiply] = new(
                NodeKind.Multiply,
                Title(NodeKind.Multiply),
                Description(NodeKind.Multiply),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Divide] = new(
                NodeKind.Divide,
                Title(NodeKind.Divide),
                Description(NodeKind.Divide),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Min] = new(
                NodeKind.Min,
                Title(NodeKind.Min),
                Description(NodeKind.Min),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Max] = new(
                NodeKind.Max,
                Title(NodeKind.Max),
                Description(NodeKind.Max),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Abs] = new(
                NodeKind.Abs,
                Title(NodeKind.Abs),
                Description(NodeKind.Abs),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.Sign] = new(
                NodeKind.Sign,
                Title(NodeKind.Sign),
                Description(NodeKind.Sign),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Cross] = new(
                NodeKind.Cross,
                Title(NodeKind.Cross),
                Description(NodeKind.Cross),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Length] = new(
                NodeKind.Length,
                Title(NodeKind.Length),
                Description(NodeKind.Length),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Distance] = new(
                NodeKind.Distance,
                Title(NodeKind.Distance),
                Description(NodeKind.Distance),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Project] = new(
                NodeKind.Project,
                Title(NodeKind.Project),
                Description(NodeKind.Project),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float3),
                    new NodePinDefinition("B", "B", GraphValueType.Float3),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float3)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Normalize] = new(
                NodeKind.Normalize,
                Title(NodeKind.Normalize),
                Description(NodeKind.Normalize),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Dot] = new(
                NodeKind.Dot,
                Title(NodeKind.Dot),
                Description(NodeKind.Dot),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Step] = new(
                NodeKind.Step,
                Title(NodeKind.Step),
                Description(NodeKind.Step),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Edge", "Edge", GraphValueType.Float1),
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [new NodePropertyDefinition("Edge", "Edge", "0.5")]),
            [NodeKind.LessThan] = new(
                NodeKind.LessThan,
                Title(NodeKind.LessThan),
                Description(NodeKind.LessThan),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text)]),
            [NodeKind.GreaterThan] = new(
                NodeKind.GreaterThan,
                Title(NodeKind.GreaterThan),
                Description(NodeKind.GreaterThan),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text)]),
            [NodeKind.LessEqual] = new(
                NodeKind.LessEqual,
                Title(NodeKind.LessEqual),
                Description(NodeKind.LessEqual),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text)]),
            [NodeKind.GreaterEqual] = new(
                NodeKind.GreaterEqual,
                Title(NodeKind.GreaterEqual),
                Description(NodeKind.GreaterEqual),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text)]),
            [NodeKind.Equal] = new(
                NodeKind.Equal,
                Title(NodeKind.Equal),
                Description(NodeKind.Equal),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Epsilon", "Epsilon", "0.0001"),
                    new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text),
                ]),
            [NodeKind.NotEqual] = new(
                NodeKind.NotEqual,
                Title(NodeKind.NotEqual),
                Description(NodeKind.NotEqual),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Epsilon", "Epsilon", "0.0001"),
                    new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text),
                ]),
            [NodeKind.SmoothStep] = new(
                NodeKind.SmoothStep,
                Title(NodeKind.SmoothStep),
                Description(NodeKind.SmoothStep),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Min", "Min", GraphValueType.Float1),
                    new NodePinDefinition("Max", "Max", GraphValueType.Float1),
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Min", "Min", "0.0"),
                    new NodePropertyDefinition("Max", "Max", "1.0"),
                ]),
            [NodeKind.Floor] = new(
                NodeKind.Floor,
                Title(NodeKind.Floor),
                Description(NodeKind.Floor),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Frac] = new(
                NodeKind.Frac,
                Title(NodeKind.Frac),
                Description(NodeKind.Frac),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Ceil] = new(
                NodeKind.Ceil,
                Title(NodeKind.Ceil),
                Description(NodeKind.Ceil),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Truncate] = new(
                NodeKind.Truncate,
                Title(NodeKind.Truncate),
                Description(NodeKind.Truncate),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Round] = new(
                NodeKind.Round,
                Title(NodeKind.Round),
                Description(NodeKind.Round),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Sine] = new(
                NodeKind.Sine,
                Title(NodeKind.Sine),
                Description(NodeKind.Sine),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Cosine] = new(
                NodeKind.Cosine,
                Title(NodeKind.Cosine),
                Description(NodeKind.Cosine),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Tangent] = new(
                NodeKind.Tangent,
                Title(NodeKind.Tangent),
                Description(NodeKind.Tangent),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ArcSine] = new(
                NodeKind.ArcSine,
                Title(NodeKind.ArcSine),
                Description(NodeKind.ArcSine),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ArcCosine] = new(
                NodeKind.ArcCosine,
                Title(NodeKind.ArcCosine),
                Description(NodeKind.ArcCosine),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ArcTangent] = new(
                NodeKind.ArcTangent,
                Title(NodeKind.ArcTangent),
                Description(NodeKind.ArcTangent),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ArcTangent2] = new(
                NodeKind.ArcTangent2,
                Title(NodeKind.ArcTangent2),
                Description(NodeKind.ArcTangent2),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Y", "Y", GraphValueType.Float4),
                    new NodePinDefinition("X", "X", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ToRadians] = new(
                NodeKind.ToRadians,
                Title(NodeKind.ToRadians),
                Description(NodeKind.ToRadians),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ToDegrees] = new(
                NodeKind.ToDegrees,
                Title(NodeKind.ToDegrees),
                Description(NodeKind.ToDegrees),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Logarithm] = new(
                NodeKind.Logarithm,
                Title(NodeKind.Logarithm),
                Description(NodeKind.Logarithm),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Exponent] = new(
                NodeKind.Exponent,
                Title(NodeKind.Exponent),
                Description(NodeKind.Exponent),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Sigmoid] = new(
                NodeKind.Sigmoid,
                Title(NodeKind.Sigmoid),
                Description(NodeKind.Sigmoid),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Value", "Value", GraphValueType.Float4),
                    new NodePinDefinition("Slope", "Slope", GraphValueType.Float1),
                    new NodePinDefinition("Center", "Center", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Type", "Type", "Float1", NodePropertyKind.Text),
                    new NodePropertyDefinition("Slope", "Slope", "1.0"),
                    new NodePropertyDefinition("Center", "Center", "0.0"),
                    new NodePropertyDefinition("OutputMin", "OutputMin", "0.0"),
                    new NodePropertyDefinition("OutputMax", "OutputMax", "1.0"),
                ]),
            [NodeKind.Softmax] = new(
                NodeKind.Softmax,
                Title(NodeKind.Softmax),
                Description(NodeKind.Softmax),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Value", "Value", GraphValueType.Float4),
                    new NodePinDefinition("Temperature", "Temperature", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Type", "Type", "Float3", NodePropertyKind.Text),
                    new NodePropertyDefinition("Temperature", "Temperature", "1.0"),
                ]),
            [NodeKind.SquareRoot] = new(
                NodeKind.SquareRoot,
                Title(NodeKind.SquareRoot),
                Description(NodeKind.SquareRoot),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ReciprocalSquareRoot] = new(
                NodeKind.ReciprocalSquareRoot,
                Title(NodeKind.ReciprocalSquareRoot),
                Description(NodeKind.ReciprocalSquareRoot),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Remap] = new(
                NodeKind.Remap,
                Title(NodeKind.Remap),
                Description(NodeKind.Remap),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("InMin", "InMin", "0.0"),
                    new NodePropertyDefinition("InMax", "InMax", "1.0"),
                    new NodePropertyDefinition("OutMin", "OutMin", "0.0"),
                    new NodePropertyDefinition("OutMax", "OutMax", "1.0"),
                    new NodePropertyDefinition("Mode", "Mode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("Clamp", "Clamp", "True", NodePropertyKind.Text),
                ]),
            [NodeKind.UvTransform] = new(
                NodeKind.UvTransform,
                Title(NodeKind.UvTransform),
                Description(NodeKind.UvTransform),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePropertyDefinition("ScaleU", "ScaleU", "1.0"),
                    new NodePropertyDefinition("ScaleV", "ScaleV", "1.0"),
                    new NodePropertyDefinition("OffsetU", "OffsetU", "0.0"),
                    new NodePropertyDefinition("OffsetV", "OffsetV", "0.0"),
                ]),
            [NodeKind.AppendFloat2] = new(
                NodeKind.AppendFloat2,
                Title(NodeKind.AppendFloat2),
                Description(NodeKind.AppendFloat2),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float2)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SplitXY] = new(
                NodeKind.SplitXY,
                Title(NodeKind.SplitXY),
                Description(NodeKind.SplitXY),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float2)],
                [
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                ],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MergeXYZ] = new(
                NodeKind.MergeXYZ,
                Title(NodeKind.MergeXYZ),
                Description(NodeKind.MergeXYZ),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                    new NodePinDefinition("Z", "Z", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float3)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MergeXYZW] = new(
                NodeKind.MergeXYZW,
                Title(NodeKind.MergeXYZW),
                Description(NodeKind.MergeXYZW),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                    new NodePinDefinition("Z", "Z", GraphValueType.Float1),
                    new NodePinDefinition("W", "W", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Modulo] = new(
                NodeKind.Modulo,
                Title(NodeKind.Modulo),
                Description(NodeKind.Modulo),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Panner] = new(
                NodeKind.Panner,
                Title(NodeKind.Panner),
                Description(NodeKind.Panner),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("Time", "Time", GraphValueType.Float1),
                ],
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePropertyDefinition("SpeedU", "SpeedU", "0.1"),
                    new NodePropertyDefinition("SpeedV", "SpeedV", "0.0"),
                ]),
            [NodeKind.UvRotate] = new(
                NodeKind.UvRotate,
                Title(NodeKind.UvRotate),
                Description(NodeKind.UvRotate),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("Angle", "Angle", GraphValueType.Float1),
                    new NodePinDefinition("Center", "Center", GraphValueType.Float2),
                ],
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePropertyDefinition("Angle", "Angle", "0.0"),
                    new NodePropertyDefinition("CenterU", "CenterU", "0.5"),
                    new NodePropertyDefinition("CenterV", "CenterV", "0.5"),
                ]),
            [NodeKind.Lerp] = new(
                NodeKind.Lerp,
                Title(NodeKind.Lerp),
                Description(NodeKind.Lerp),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                    new NodePinDefinition("T", "T", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("T", "T", "0.5"),
                    new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text),
                ]),
            [NodeKind.VectorMix] = new(
                NodeKind.VectorMix,
                Title(NodeKind.VectorMix),
                Description(NodeKind.VectorMix),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float3),
                    new NodePinDefinition("B", "B", GraphValueType.Float3),
                    new NodePinDefinition("T", "T", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float3)],
                [new NodePropertyDefinition("T", "T", "0.5")]),
            [NodeKind.Saturate] = new(
                NodeKind.Saturate,
                Title(NodeKind.Saturate),
                Description(NodeKind.Saturate),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.OneMinus] = new(
                NodeKind.OneMinus,
                Title(NodeKind.OneMinus),
                Description(NodeKind.OneMinus),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text)]),
            [NodeKind.SplitColor] = new(
                NodeKind.SplitColor,
                Title(NodeKind.SplitColor),
                Description(NodeKind.SplitColor),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SplitXYZ] = new(
                NodeKind.SplitXYZ,
                Title(NodeKind.SplitXYZ),
                Description(NodeKind.SplitXYZ),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float3)],
                [
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                    new NodePinDefinition("Z", "Z", GraphValueType.Float1),
                ],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SplitXYZW] = new(
                NodeKind.SplitXYZW,
                Title(NodeKind.SplitXYZW),
                Description(NodeKind.SplitXYZW),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                    new NodePinDefinition("Z", "Z", GraphValueType.Float1),
                    new NodePinDefinition("W", "W", GraphValueType.Float1),
                ],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ComposeColor] = new(
                NodeKind.ComposeColor,
                Title(NodeKind.ComposeColor),
                Description(NodeKind.ComposeColor),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Clamp] = new(
                NodeKind.Clamp,
                Title(NodeKind.Clamp),
                Description(NodeKind.Clamp),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Min", "Min", "0.0"),
                    new NodePropertyDefinition("Max", "Max", "1.0"),
                    new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text),
                ]),
            [NodeKind.Power] = new(
                NodeKind.Power,
                Title(NodeKind.Power),
                Description(NodeKind.Power),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Value", "Value", GraphValueType.Float4),
                    new NodePinDefinition("Exponent", "Exponent", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Exponent", "Exponent", "2.0"),
                    new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text),
                ]),
            [NodeKind.Fresnel] = new(
                NodeKind.Fresnel,
                Title(NodeKind.Fresnel),
                Description(NodeKind.Fresnel),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("ViewDir", "ViewDir", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Power", "Power", "5.0"),
                    new NodePropertyDefinition("Bias", "Bias", "0.0"),
                ]),
            [NodeKind.ColorRamp] = new(
                NodeKind.ColorRamp,
                Title(NodeKind.ColorRamp),
                Description(NodeKind.ColorRamp),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("A", "A", GraphValueType.Float4),
                    new NodePinDefinition("B", "B", GraphValueType.Float4),
                    new NodePinDefinition("T", "T", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("StartR", "StartR", "0.0"),
                    new NodePropertyDefinition("StartG", "StartG", "0.0"),
                    new NodePropertyDefinition("StartB", "StartB", "0.0"),
                    new NodePropertyDefinition("StartA", "StartA", "1.0"),
                    new NodePropertyDefinition("EndR", "EndR", "1.0"),
                    new NodePropertyDefinition("EndG", "EndG", "1.0"),
                    new NodePropertyDefinition("EndB", "EndB", "1.0"),
                    new NodePropertyDefinition("EndA", "EndA", "1.0"),
                    new NodePropertyDefinition("StopCount", "Stop Count", "2", NodePropertyKind.Text),
                    new NodePropertyDefinition("Mid1", "Mid 1 Position", "0.25"),
                    new NodePropertyDefinition("Mid1R", "Mid 1 R", "0.25"),
                    new NodePropertyDefinition("Mid1G", "Mid 1 G", "0.25"),
                    new NodePropertyDefinition("Mid1B", "Mid 1 B", "0.25"),
                    new NodePropertyDefinition("Mid1A", "Mid 1 A", "1.0"),
                    new NodePropertyDefinition("Mid2", "Mid 2 Position", "0.5"),
                    new NodePropertyDefinition("Mid2R", "Mid 2 R", "0.5"),
                    new NodePropertyDefinition("Mid2G", "Mid 2 G", "0.5"),
                    new NodePropertyDefinition("Mid2B", "Mid 2 B", "0.5"),
                    new NodePropertyDefinition("Mid2A", "Mid 2 A", "1.0"),
                    new NodePropertyDefinition("Mid3", "Mid 3 Position", "0.75"),
                    new NodePropertyDefinition("Mid3R", "Mid 3 R", "0.75"),
                    new NodePropertyDefinition("Mid3G", "Mid 3 G", "0.75"),
                    new NodePropertyDefinition("Mid3B", "Mid 3 B", "0.75"),
                    new NodePropertyDefinition("Mid3A", "Mid 3 A", "1.0"),
                    new NodePropertyDefinition("Start", "Start", "0.0"),
                    new NodePropertyDefinition("End", "End", "1.0"),
                    new NodePropertyDefinition("Mode", "Mode", "Linear", NodePropertyKind.Text),
                ]),
            [NodeKind.LayerBlend] = new(
                NodeKind.LayerBlend,
                Title(NodeKind.LayerBlend),
                Description(NodeKind.LayerBlend),
                NodeCategory.Math,
                Color.FromArgb(118, 126, 184),
                [
                    new NodePinDefinition("Background", "Background", GraphValueType.Float4),
                    new NodePinDefinition("Foreground", "Foreground", GraphValueType.Float4),
                    new NodePinDefinition("Opacity", "Opacity", GraphValueType.Float1),
                    new NodePinDefinition("Mask", "Mask", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("LayerMode", "Layer Mode", "Normal", NodePropertyKind.Text),
                    new NodePropertyDefinition("MaskInvert", "Invert Mask", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.ComponentMask] = new(
                NodeKind.ComponentMask,
                Title(NodeKind.ComponentMask),
                Description(NodeKind.ComponentMask),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float4)],
                [new NodePropertyDefinition("Channels", "Channels", "RGBA", NodePropertyKind.Text)]),
            [NodeKind.BoxMask] = new(
                NodeKind.BoxMask,
                Title(NodeKind.BoxMask),
                Description(NodeKind.BoxMask),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Position", "Position", GraphValueType.Float4),
                    new NodePinDefinition("Center", "Center", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("CenterX", "CenterX", "0.0"),
                    new NodePropertyDefinition("CenterY", "CenterY", "0.0"),
                    new NodePropertyDefinition("CenterZ", "CenterZ", "0.0"),
                    new NodePropertyDefinition("SizeX", "SizeX", "1.0"),
                    new NodePropertyDefinition("SizeY", "SizeY", "1.0"),
                    new NodePropertyDefinition("SizeZ", "SizeZ", "1.0"),
                    new NodePropertyDefinition("Falloff", "Falloff", "0.1"),
                    new NodePropertyDefinition("Invert", "Invert", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.SphereMask] = new(
                NodeKind.SphereMask,
                Title(NodeKind.SphereMask),
                Description(NodeKind.SphereMask),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Position", "Position", GraphValueType.Float4),
                    new NodePinDefinition("Center", "Center", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("CenterX", "CenterX", "0.0"),
                    new NodePropertyDefinition("CenterY", "CenterY", "0.0"),
                    new NodePropertyDefinition("CenterZ", "CenterZ", "0.0"),
                    new NodePropertyDefinition("Radius", "Radius", "1.0"),
                    new NodePropertyDefinition("Falloff", "Falloff", "0.1"),
                    new NodePropertyDefinition("Invert", "Invert", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.SlopeMask] = new(
                NodeKind.SlopeMask,
                Title(NodeKind.SlopeMask),
                Description(NodeKind.SlopeMask),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("Up", "Up", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Axis", "Axis", "Y", NodePropertyKind.Text),
                    new NodePropertyDefinition("Bias", "Bias", "0.0"),
                    new NodePropertyDefinition("Sharpness", "Sharpness", "1.0"),
                    new NodePropertyDefinition("Invert", "Invert", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.RgbCurve] = new(
                NodeKind.RgbCurve,
                Title(NodeKind.RgbCurve),
                Description(NodeKind.RgbCurve),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("InMin", "InMin", "0.0"),
                    new NodePropertyDefinition("Gamma", "Gamma", "1.0"),
                    new NodePropertyDefinition("InMax", "InMax", "1.0"),
                    new NodePropertyDefinition("OutMin", "OutMin", "0.0"),
                    new NodePropertyDefinition("OutMax", "OutMax", "1.0"),
                ]),
            [NodeKind.ColorAdjust] = new(
                NodeKind.ColorAdjust,
                Title(NodeKind.ColorAdjust),
                Description(NodeKind.ColorAdjust),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Exposure", "Exposure", "0.0"),
                    new NodePropertyDefinition("HueShift", "HueShift", "0.0"),
                    new NodePropertyDefinition("Temperature", "Temperature", "0.0"),
                    new NodePropertyDefinition("Tint", "Tint", "0.0"),
                    new NodePropertyDefinition("Contrast", "Contrast", "1.0"),
                    new NodePropertyDefinition("Saturation", "Saturation", "1.0"),
                    new NodePropertyDefinition("ShadowLift", "ShadowLift", "0.0"),
                    new NodePropertyDefinition("HighlightCompress", "HighlightCompress", "0.0"),
                    new NodePropertyDefinition("Lift", "Lift", "0.0"),
                    new NodePropertyDefinition("Gamma", "Gamma", "1.0"),
                    new NodePropertyDefinition("Gain", "Gain", "1.0"),
                ]),
            [NodeKind.TonemapLite] = new(
                NodeKind.TonemapLite,
                Title(NodeKind.TonemapLite),
                Description(NodeKind.TonemapLite),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Operator", "Operator", "ACESApprox", NodePropertyKind.Text),
                    new NodePropertyDefinition("Exposure", "Exposure", "0.0"),
                    new NodePropertyDefinition("WhitePoint", "WhitePoint", "1.5"),
                    new NodePropertyDefinition("Gamma", "Gamma", "1.0"),
                ]),
            [NodeKind.Reflect] = new(
                NodeKind.Reflect,
                Title(NodeKind.Reflect),
                Description(NodeKind.Reflect),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Incident", "Incident", GraphValueType.Float3),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float3),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float3)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.DirectionToLatLongUv] = new(
                NodeKind.DirectionToLatLongUv,
                Title(NodeKind.DirectionToLatLongUv),
                Description(NodeKind.DirectionToLatLongUv),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Direction", "Direction", GraphValueType.Float4),
                    new NodePinDefinition("Rotation", "Rotation", GraphValueType.Float1),
                    new NodePinDefinition("Horizon", "Horizon", GraphValueType.Float1),
                ],
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePropertyDefinition("Rotation", "Rotation", "0.0"),
                    new NodePropertyDefinition("Horizon", "Horizon", "0.0"),
                ]),
            [NodeKind.Refract] = new(
                NodeKind.Refract,
                Title(NodeKind.Refract),
                Description(NodeKind.Refract),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Incident", "Incident", GraphValueType.Float3),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float3),
                    new NodePinDefinition("Eta", "Eta", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float3)],
                [new NodePropertyDefinition("Eta", "Eta", "1.33")]),
            [NodeKind.FaceForward] = new(
                NodeKind.FaceForward,
                Title(NodeKind.FaceForward),
                Description(NodeKind.FaceForward),
                NodeCategory.Math,
                Color.FromArgb(96, 132, 166),
                [
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float3),
                    new NodePinDefinition("Incident", "Incident", GraphValueType.Float3),
                    new NodePinDefinition("Reference", "Reference", GraphValueType.Float3),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float3)],
                Array.Empty<NodePropertyDefinition>()),
        })
        {
            definitions[pair.Key] = pair.Value;
        }
    }
}
