using System.Drawing;

namespace RayMmdNodeEditor.Graph;

public static partial class NodeRegistry
{
    private static void AddControlOutputDefinitions(Dictionary<NodeKind, NodeDefinition> definitions)
    {
        foreach (var pair in new Dictionary<NodeKind, NodeDefinition>
        {
            [NodeKind.ControlObjectPosition] = new(
                NodeKind.ControlObjectPosition,
                Title(NodeKind.ControlObjectPosition),
                Description(NodeKind.ControlObjectPosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "Target.x", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "XYZ", NodePropertyKind.Text),
                ]),
            [NodeKind.ControlObjectValue] = new(
                NodeKind.ControlObjectValue,
                Title(NodeKind.ControlObjectValue),
                Description(NodeKind.ControlObjectValue),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Name", "Name", "Line.x", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "Si", NodePropertyKind.Text),
                ]),
            [NodeKind.SharedParameter] = new(
                NodeKind.SharedParameter,
                Title(NodeKind.SharedParameter),
                Description(NodeKind.SharedParameter),
                NodeCategory.Input,
                Color.FromArgb(140, 122, 190),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                [
                    new NodePropertyDefinition("Name", "Name", "SharedValue", NodePropertyKind.Text),
                    new NodePropertyDefinition("DefaultValue", "DefaultValue", "0.0"),
                ]),
            [NodeKind.ControlObjectRotation] = new(
                NodeKind.ControlObjectRotation,
                Title(NodeKind.ControlObjectRotation),
                Description(NodeKind.ControlObjectRotation),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "Line.x", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "Rxyz", NodePropertyKind.Text),
                ]),
            [NodeKind.ControllerLightDirection] = new(
                NodeKind.ControllerLightDirection,
                Title(NodeKind.ControllerLightDirection),
                Description(NodeKind.ControllerLightDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "XYZ", NodePropertyKind.Text),
                    new NodePropertyDefinition("BaseX", "BaseX", "0.0"),
                    new NodePropertyDefinition("BaseY", "BaseY", "0.0"),
                    new NodePropertyDefinition("BaseZ", "BaseZ", "1.0"),
                ]),
            [NodeKind.ControlObjectVector] = new(
                NodeKind.ControlObjectVector,
                Title(NodeKind.ControlObjectVector),
                Description(NodeKind.ControlObjectVector),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "Light Direction XYZ", NodePropertyKind.Text),
                ]),
            [NodeKind.ControlObjectBonePosition] = new(
                NodeKind.ControlObjectBonePosition,
                Title(NodeKind.ControlObjectBonePosition),
                Description(NodeKind.ControlObjectBonePosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "Direction", NodePropertyKind.Text),
                ]),
            [NodeKind.PointLightDirection] = new(
                NodeKind.PointLightDirection,
                Title(NodeKind.PointLightDirection),
                Description(NodeKind.PointLightDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [new NodePinDefinition("LightPos", "LightPos", GraphValueType.Float4)],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.TransformPosition] = new(
                NodeKind.TransformPosition,
                Title(NodeKind.TransformPosition),
                Description(NodeKind.TransformPosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [new NodePinDefinition("Position", "Position", GraphValueType.Float4)],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("SourceSpace", "SourceSpace", "Local", NodePropertyKind.Text),
                    new NodePropertyDefinition("TargetSpace", "TargetSpace", "World", NodePropertyKind.Text),
                ]),
            [NodeKind.TransformVector] = new(
                NodeKind.TransformVector,
                Title(NodeKind.TransformVector),
                Description(NodeKind.TransformVector),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [new NodePinDefinition("Vector", "Vector", GraphValueType.Float4)],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("VectorType", "VectorType", "Direction", NodePropertyKind.Text),
                    new NodePropertyDefinition("SourceSpace", "SourceSpace", "World", NodePropertyKind.Text),
                    new NodePropertyDefinition("TargetSpace", "TargetSpace", "View", NodePropertyKind.Text),
                    new NodePropertyDefinition("NormalizeOutput", "NormalizeOutput", "True", NodePropertyKind.Text),
                ]),
            [NodeKind.ControlObjectTransformDirection] = new(
                NodeKind.ControlObjectTransformDirection,
                Title(NodeKind.ControlObjectTransformDirection),
                Description(NodeKind.ControlObjectTransformDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("Axis", "Axis", "Z", NodePropertyKind.Text),
                ]),
            [NodeKind.ControlObjectBoneDirection] = new(
                NodeKind.ControlObjectBoneDirection,
                Title(NodeKind.ControlObjectBoneDirection),
                Description(NodeKind.ControlObjectBoneDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "Direction", NodePropertyKind.Text),
                    new NodePropertyDefinition("Axis", "Axis", "Z", NodePropertyKind.Text),
                ]),
            [NodeKind.ControlObjectCenter] = new(
                NodeKind.ControlObjectCenter,
                Title(NodeKind.ControlObjectCenter),
                Description(NodeKind.ControlObjectCenter),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("Item", "Item", "\u5168\u3066\u306e\u89AA", NodePropertyKind.Text),
                ]),
            [NodeKind.ControlObjectAngleDirection] = new(
                NodeKind.ControlObjectAngleDirection,
                Title(NodeKind.ControlObjectAngleDirection),
                Description(NodeKind.ControlObjectAngleDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "LightController.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("UpItem", "UpItem", "ShadowUp", NodePropertyKind.Text),
                    new NodePropertyDefinition("DownItem", "DownItem", "ShadowBottom", NodePropertyKind.Text),
                    new NodePropertyDefinition("LeftItem", "LeftItem", "ShadowLeft", NodePropertyKind.Text),
                    new NodePropertyDefinition("RightItem", "RightItem", "ShadowRight", NodePropertyKind.Text),
                ]),
            [NodeKind.TextureAddValueNode] = new(
                NodeKind.TextureAddValueNode,
                Title(NodeKind.TextureAddValueNode),
                Description(NodeKind.TextureAddValueNode),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.TextureMulValueNode] = new(
                NodeKind.TextureMulValueNode,
                Title(NodeKind.TextureMulValueNode),
                Description(NodeKind.TextureMulValueNode),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SphereAddValueNode] = new(
                NodeKind.SphereAddValueNode,
                Title(NodeKind.SphereAddValueNode),
                Description(NodeKind.SphereAddValueNode),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SphereMulValueNode] = new(
                NodeKind.SphereMulValueNode,
                Title(NodeKind.SphereMulValueNode),
                Description(NodeKind.SphereMulValueNode),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Output] = new(
                NodeKind.Output,
                Title(NodeKind.Output),
                Description(NodeKind.Output),
                NodeCategory.Output,
                Color.FromArgb(168, 84, 84),
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("CaptureColor", "CaptureColor", GraphValueType.Float4),
                    new NodePinDefinition("CaptureSecondaryColor", "CaptureSecondaryColor", GraphValueType.Float4),
                    new NodePinDefinition("SecondaryColor", "SecondaryColor", GraphValueType.Float4),
                    new NodePinDefinition("Alpha", "Alpha", GraphValueType.Float1),
                    new NodePinDefinition("VertexOffset", "VertexOffset", GraphValueType.Float4),
                ],
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePropertyDefinition("Pipeline", "Pipeline", "Object", NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaMode", "AlphaMode", "Opaque", NodePropertyKind.Text),
                    new NodePropertyDefinition("CullMode", "CullMode", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("ZEnable", "ZEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaTestEnable", "AlphaTestEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaBlendEnable", "AlphaBlendEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("SrcBlend", "SrcBlend", "SRCALPHA", NodePropertyKind.Text),
                    new NodePropertyDefinition("DestBlend", "DestBlend", "INVSRCALPHA", NodePropertyKind.Text),
                    new NodePropertyDefinition("BlendOp", "BlendOp", "ADD", NodePropertyKind.Text),
                    new NodePropertyDefinition("ZWriteEnable", "ZWriteEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget0Name", "RenderTarget0Name", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget0Scale", "RenderTarget0Scale", "1.0"),
                    new NodePropertyDefinition("RenderTarget1Name", "RenderTarget1Name", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget1Scale", "RenderTarget1Scale", "1.0"),
                    new NodePropertyDefinition("SkipPresentDraw", "SkipPresentDraw", "False", NodePropertyKind.Text),
                    new NodePropertyDefinition("ClearTargets", "ClearTargets", "False", NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaClipThreshold", "AlphaClipThreshold", "0.0"),
                    new NodePropertyDefinition("Subset", "Subset", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TargetModelName", "TargetModelName", "REPLACE_TARGET_MODEL.pmx", NodePropertyKind.Text),
                    new NodePropertyDefinition("HairSubset", "HairSubset", "REPLACE_HAIR_SUBSET", NodePropertyKind.Text),
                    new NodePropertyDefinition("HairPushDistance", "HairPushDistance", "3.0"),
                    new NodePropertyDefinition("EyeBoost", "EyeBoost", "1.0"),
                    new NodePropertyDefinition("VisibilitySpeed", "VisibilitySpeed", "3.0"),
                    new NodePropertyDefinition("VisibilityOffset", "VisibilityOffset", "0.0"),
                    new NodePropertyDefinition("ComposeAlpha", "ComposeAlpha", "1.0"),
                    new NodePropertyDefinition("TechniqueStyle", "TechniqueStyle", "Modern", NodePropertyKind.Text),
                    new NodePropertyDefinition("ShadowTechniqueMode", "ShadowTechniqueMode", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("ZplotTechniqueMode", "ZplotTechniqueMode", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("VdsQualityPreset", "VDS Quality Preset", "VDS_QUALITY_HIGH", NodePropertyKind.Text),
                    new NodePropertyDefinition("VdsNearExtentScale", "VDS Near Extent", "0.75"),
                    new NodePropertyDefinition("VdsFarExtentScale", "VDS Far Extent", "2.75"),
                    new NodePropertyDefinition("VdsNearDepthScale", "VDS Near Depth", "0.85"),
                    new NodePropertyDefinition("VdsFarDepthScale", "VDS Far Depth", "3.50"),
                    new NodePropertyDefinition("VdsBlendStart", "VDS Blend Start", "0.55"),
                    new NodePropertyDefinition("VdsBlendEnd", "VDS Blend End", "0.90"),
                ]),
            [NodeKind.MaterialOutput] = new(
                NodeKind.MaterialOutput,
                Title(NodeKind.MaterialOutput),
                Description(NodeKind.MaterialOutput),
                NodeCategory.Output,
                Color.FromArgb(168, 84, 84),
                [
                    new NodePinDefinition("Surface", "Surface", GraphValueType.Material),
                    new NodePinDefinition("VertexOffset", "VertexOffset", GraphValueType.Float4),
                ],
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePropertyDefinition("ShadingMode", "ShadingMode", "Full", NodePropertyKind.Text),
                    new NodePropertyDefinition("CullMode", "CullMode", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("ZEnable", "ZEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaTestEnable", "AlphaTestEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaBlendEnable", "AlphaBlendEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("SrcBlend", "SrcBlend", "SRCALPHA", NodePropertyKind.Text),
                    new NodePropertyDefinition("DestBlend", "DestBlend", "INVSRCALPHA", NodePropertyKind.Text),
                    new NodePropertyDefinition("BlendOp", "BlendOp", "ADD", NodePropertyKind.Text),
                    new NodePropertyDefinition("ZWriteEnable", "ZWriteEnable", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget0Name", "RenderTarget0Name", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget0Scale", "RenderTarget0Scale", "1.0"),
                    new NodePropertyDefinition("RenderTarget0Mode", "RenderTarget0Mode", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget1Name", "RenderTarget1Name", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("RenderTarget1Scale", "RenderTarget1Scale", "1.0"),
                    new NodePropertyDefinition("SecondaryOutputMode", "SecondaryOutputMode", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("AlphaClipThreshold", "AlphaClipThreshold", "0.0"),
                    new NodePropertyDefinition("Subset", "Subset", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TechniqueStyle", "TechniqueStyle", "Modern", NodePropertyKind.Text),
                    new NodePropertyDefinition("ShadowTechniqueMode", "ShadowTechniqueMode", "Auto", NodePropertyKind.Text),
                    new NodePropertyDefinition("ZplotTechniqueMode", "ZplotTechniqueMode", "Auto", NodePropertyKind.Text),
                ]),
            [NodeKind.Reroute] = new(
                NodeKind.Reroute,
                Title(NodeKind.Reroute),
                Description(NodeKind.Reroute),
                NodeCategory.Math,
                Color.FromArgb(120, 128, 138),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.Frame] = new(
                NodeKind.Frame,
                Title(NodeKind.Frame),
                Description(NodeKind.Frame),
                NodeCategory.Experimental,
                Color.FromArgb(98, 132, 184),
                Array.Empty<NodePinDefinition>(),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePropertyDefinition("Title", "Title", "Frame", NodePropertyKind.Text),
                    new NodePropertyDefinition("Width", "Width", "420.0"),
                    new NodePropertyDefinition("Height", "Height", "240.0"),
                    new NodePropertyDefinition("TintR", "TintR", "0.36"),
                    new NodePropertyDefinition("TintG", "TintG", "0.52"),
                    new NodePropertyDefinition("TintB", "TintB", "0.86"),
                    new NodePropertyDefinition("Opacity", "Opacity", "0.16"),
                ]),
            [NodeKind.Group] = new(
                NodeKind.Group,
                Title(NodeKind.Group),
                Description(NodeKind.Group),
                NodeCategory.Experimental,
                Color.FromArgb(110, 120, 168),
                Array.Empty<NodePinDefinition>(),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePropertyDefinition("GroupId", "GroupId", string.Empty, NodePropertyKind.Text, NodePropertyEditorKind.Hidden),
                    new NodePropertyDefinition("GroupName", "GroupName", "Group", NodePropertyKind.Text),
                ]),
            [NodeKind.GroupInput] = new(
                NodeKind.GroupInput,
                Title(NodeKind.GroupInput),
                Description(NodeKind.GroupInput),
                NodeCategory.Input,
                Color.FromArgb(112, 138, 190),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Name", "Name", "Input", NodePropertyKind.Text, NodePropertyEditorKind.Hidden),
                    new NodePropertyDefinition("DisplayName", "DisplayName", "Input", NodePropertyKind.Text),
                    new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text),
                ]),
            [NodeKind.GroupOutput] = new(
                NodeKind.GroupOutput,
                Title(NodeKind.GroupOutput),
                Description(NodeKind.GroupOutput),
                NodeCategory.Output,
                Color.FromArgb(168, 110, 110),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePropertyDefinition("Name", "Name", "Output", NodePropertyKind.Text, NodePropertyEditorKind.Hidden),
                    new NodePropertyDefinition("DisplayName", "DisplayName", "Output", NodePropertyKind.Text),
                    new NodePropertyDefinition("Type", "Type", "Float4", NodePropertyKind.Text),
                ]),
        })
        {
            definitions[pair.Key] = pair.Value;
        }
    }
}
