using System.Drawing;

namespace RayMmdNodeEditor.Graph;

public static partial class NodeRegistry
{
    private static void AddTextureDefinitions(Dictionary<NodeKind, NodeDefinition> definitions)
    {
        foreach (var pair in new Dictionary<NodeKind, NodeDefinition>
        {
            [NodeKind.MaterialTexture] = new(
                NodeKind.MaterialTexture,
                Title(NodeKind.MaterialTexture),
                Description(NodeKind.MaterialTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text),
                ]),
            [NodeKind.ExternalTexture] = new(
                NodeKind.ExternalTexture,
                Title(NodeKind.ExternalTexture),
                Description(NodeKind.ExternalTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("LOD", "LOD", GraphValueType.Float1),
                ],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("ResourceName", "ResourceName", "mask.png", NodePropertyKind.Text),
                    new NodePropertyDefinition("SourcePath", "SourcePath", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TextureMode", "TextureMode", "Static", NodePropertyKind.Text),
                    new NodePropertyDefinition("AddressMode", "AddressMode", "Wrap", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("MipLevels", "MipLevels", "1"),
                    new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text),
                ]),
            [NodeKind.MatCapAtlasSample] = new(
                NodeKind.MatCapAtlasSample,
                Title(NodeKind.MatCapAtlasSample),
                Description(NodeKind.MatCapAtlasSample),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("Index", "Index", GraphValueType.Float1),
                    new NodePinDefinition("MipControl", "MipControl", GraphValueType.Float1),
                ],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("ResourceName", "ResourceName", "matcap_atlas.dds", NodePropertyKind.Text),
                    new NodePropertyDefinition("SourcePath", "SourcePath", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TextureMode", "TextureMode", "Static", NodePropertyKind.Text),
                    new NodePropertyDefinition("AddressMode", "AddressMode", "Clamp", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("MipLevels", "MipLevels", "0"),
                    new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text),
                    new NodePropertyDefinition("IndexMode", "IndexMode", "Mask", NodePropertyKind.Text),
                    new NodePropertyDefinition("AtlasColumns", "AtlasColumns", "4.0"),
                    new NodePropertyDefinition("AtlasRows", "AtlasRows", "4.0"),
                    new NodePropertyDefinition("ManualColumn", "ManualColumn", "0.0"),
                    new NodePropertyDefinition("ManualRow", "ManualRow", "0.0"),
                    new NodePropertyDefinition("Padding", "Padding", "0.0025"),
                    new NodePropertyDefinition("ManualMipLevel", "ManualMipLevel", "0", NodePropertyKind.Text),
                    new NodePropertyDefinition("MaxMipLevel", "MaxMipLevel", "8.0"),
                    new NodePropertyDefinition("FlipY", "FlipY", "True", NodePropertyKind.Text),
                ]),
            [NodeKind.SharedTextureSample] = new(
                NodeKind.SharedTextureSample,
                Title(NodeKind.SharedTextureSample),
                Description(NodeKind.SharedTextureSample),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("LOD", "LOD", GraphValueType.Float1),
                ],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("BufferName", "BufferName", "SharedTexture", NodePropertyKind.Text),
                    new NodePropertyDefinition("Format", "Format", "A16B16G16R16F", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("MipLevels", "MipLevels", "1"),
                ]),
            [NodeKind.DiffuseEnvSample] = new(
                NodeKind.DiffuseEnvSample,
                Title(NodeKind.DiffuseEnvSample),
                Description(NodeKind.DiffuseEnvSample),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Direction", "Direction", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("BufferName", "BufferName", "EnvDiffuse", NodePropertyKind.Text),
                    new NodePropertyDefinition("Format", "Format", "A16B16G16R16F", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                ]),
            [NodeKind.DiffuseEnvBake] = new(
                NodeKind.DiffuseEnvBake,
                Title(NodeKind.DiffuseEnvBake),
                Description(NodeKind.DiffuseEnvBake),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("SourceBufferName", "SourceBufferName", "SkyLatLong", NodePropertyKind.Text),
                    new NodePropertyDefinition("Format", "Format", "A16B16G16R16F", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                ]),
            [NodeKind.SpecularEnvSample] = new(
                NodeKind.SpecularEnvSample,
                Title(NodeKind.SpecularEnvSample),
                Description(NodeKind.SpecularEnvSample),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("ViewDir", "ViewDir", GraphValueType.Float4),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("Roughness", "Roughness", GraphValueType.Float1),
                ],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("BufferName", "BufferName", "EnvSpecular", NodePropertyKind.Text),
                    new NodePropertyDefinition("Format", "Format", "A16B16G16R16F", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("Roughness", "Roughness", "0.5"),
                    new NodePropertyDefinition("MaxLod", "MaxLod", "7.0"),
                    new NodePropertyDefinition("LodBias", "LodBias", "0.0"),
                ]),
            [NodeKind.SpecularEnvBake] = new(
                NodeKind.SpecularEnvBake,
                Title(NodeKind.SpecularEnvBake),
                Description(NodeKind.SpecularEnvBake),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("SourceBufferName", "SourceBufferName", "SkyLatLong", NodePropertyKind.Text),
                    new NodePropertyDefinition("Format", "Format", "A16B16G16R16F", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("Roughness", "Roughness", "0.5"),
                    new NodePropertyDefinition("SampleSpread", "SampleSpread", "0.35"),
                ]),
            [NodeKind.TriplanarBoxmap] = new(
                NodeKind.TriplanarBoxmap,
                Title(NodeKind.TriplanarBoxmap),
                Description(NodeKind.TriplanarBoxmap),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("Texture", "Texture", GraphValueType.Float4),
                    new NodePinDefinition("Position", "Position", GraphValueType.Float4),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                ],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("TextureSource", "TextureSource", "Material", NodePropertyKind.Text),
                    new NodePropertyDefinition("ResourceName", "ResourceName", "boxmap.png", NodePropertyKind.Text),
                    new NodePropertyDefinition("SourcePath", "SourcePath", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TextureMode", "TextureMode", "Static", NodePropertyKind.Text),
                    new NodePropertyDefinition("AddressMode", "AddressMode", "Wrap", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "1.0"),
                    new NodePropertyDefinition("BlendSharpness", "BlendSharpness", "4.0"),
                ]),
            [NodeKind.NoiseTexture] = new(
                NodeKind.NoiseTexture,
                Title(NodeKind.NoiseTexture),
                Description(NodeKind.NoiseTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("NoiseType", "NoiseType", "Perlin", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                ]),
            [NodeKind.DomainWarp] = new(
                NodeKind.DomainWarp,
                Title(NodeKind.DomainWarp),
                Description(NodeKind.DomainWarp),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Coord", "Coord", GraphValueType.Float4),
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("NoiseType", "NoiseType", "Perlin", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "4.0"),
                    new NodePropertyDefinition("Strength", "Strength", "0.25"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                ]),
            [NodeKind.VoronoiTexture] = new(
                NodeKind.VoronoiTexture,
                Title(NodeKind.VoronoiTexture),
                Description(NodeKind.VoronoiTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                    new NodePropertyDefinition("Jitter", "Jitter", "1.0"),
                ]),
            [NodeKind.FbmNoise] = new(
                NodeKind.FbmNoise,
                Title(NodeKind.FbmNoise),
                Description(NodeKind.FbmNoise),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("NoiseType", "NoiseType", "Perlin", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("FractalMode", "FractalMode", "FBM", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                    new NodePropertyDefinition("Octaves", "Octaves", "4.0"),
                    new NodePropertyDefinition("Lacunarity", "Lacunarity", "2.0"),
                    new NodePropertyDefinition("Gain", "Gain", "0.5"),
                ]),
            [NodeKind.MusgraveTexture] = new(
                NodeKind.MusgraveTexture,
                Title(NodeKind.MusgraveTexture),
                Description(NodeKind.MusgraveTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("NoiseType", "NoiseType", "Perlin", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("MusgraveType", "MusgraveType", "FBM", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                    new NodePropertyDefinition("Octaves", "Octaves", "4.0"),
                    new NodePropertyDefinition("Lacunarity", "Lacunarity", "2.0"),
                    new NodePropertyDefinition("Gain", "Gain", "0.5"),
                    new NodePropertyDefinition("Offset", "Offset", "0.7"),
                ]),
            [NodeKind.CellEdgeTexture] = new(
                NodeKind.CellEdgeTexture,
                Title(NodeKind.CellEdgeTexture),
                Description(NodeKind.CellEdgeTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Distance", "Distance", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "6.0"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                    new NodePropertyDefinition("Jitter", "Jitter", "1.0"),
                    new NodePropertyDefinition("EdgeWidth", "EdgeWidth", "0.08"),
                    new NodePropertyDefinition("EdgeSoftness", "EdgeSoftness", "0.04"),
                ]),
            [NodeKind.CurlNoise] = new(
                NodeKind.CurlNoise,
                Title(NodeKind.CurlNoise),
                Description(NodeKind.CurlNoise),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Vector", "Vector", GraphValueType.Float4),
                    new NodePinDefinition("Magnitude", "Magnitude", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("NoiseType", "NoiseType", "Perlin", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "4.0"),
                    new NodePropertyDefinition("Strength", "Strength", "0.4"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                    new NodePropertyDefinition("Epsilon", "Epsilon", "0.05"),
                ]),
            [NodeKind.AnisotropicNoise] = new(
                NodeKind.AnisotropicNoise,
                Title(NodeKind.AnisotropicNoise),
                Description(NodeKind.AnisotropicNoise),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("Coord", "Coord", GraphValueType.Float4),
                    new NodePinDefinition("Direction", "Direction", GraphValueType.Float4),
                ],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("NoiseType", "NoiseType", "Perlin", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("Seed", "Seed", "0.0"),
                    new NodePropertyDefinition("Octaves", "Octaves", "4.0"),
                    new NodePropertyDefinition("Lacunarity", "Lacunarity", "2.0"),
                    new NodePropertyDefinition("Gain", "Gain", "0.5"),
                    new NodePropertyDefinition("Anisotropy", "Anisotropy", "3.0"),
                ]),
            [NodeKind.GradientTexture] = new(
                NodeKind.GradientTexture,
                Title(NodeKind.GradientTexture),
                Description(NodeKind.GradientTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("GradientType", "GradientType", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "1.0"),
                ]),
            [NodeKind.CheckerTexture] = new(
                NodeKind.CheckerTexture,
                Title(NodeKind.CheckerTexture),
                Description(NodeKind.CheckerTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "4.0"),
                ]),
            [NodeKind.BrickTexture] = new(
                NodeKind.BrickTexture,
                Title(NodeKind.BrickTexture),
                Description(NodeKind.BrickTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("BrickWidth", "BrickWidth", "0.45"),
                    new NodePropertyDefinition("BrickHeight", "BrickHeight", "0.22"),
                    new NodePropertyDefinition("Mortar", "Mortar", "0.04"),
                    new NodePropertyDefinition("Offset", "Offset", "0.5"),
                ]),
            [NodeKind.WaveTexture] = new(
                NodeKind.WaveTexture,
                Title(NodeKind.WaveTexture),
                Description(NodeKind.WaveTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Coord", "Coord", GraphValueType.Float4)],
                [
                    new NodePinDefinition("Factor", "Factor", GraphValueType.Float1),
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                ],
                [
                    new NodePropertyDefinition("WaveType", "WaveType", "Bands", NodePropertyKind.Text),
                    new NodePropertyDefinition("WaveProfile", "WaveProfile", "Sine", NodePropertyKind.Text),
                    new NodePropertyDefinition("Dimensions", "Dimensions", "2D", NodePropertyKind.Text),
                    new NodePropertyDefinition("Scale", "Scale", "5.0"),
                    new NodePropertyDefinition("Distortion", "Distortion", "0.0"),
                ]),
            [NodeKind.MaterialSphereMap] = new(
                NodeKind.MaterialSphereMap,
                Title(NodeKind.MaterialSphereMap),
                Description(NodeKind.MaterialSphereMap),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text)]),
            [NodeKind.MaterialToonTexture] = new(
                NodeKind.MaterialToonTexture,
                Title(NodeKind.MaterialToonTexture),
                Description(NodeKind.MaterialToonTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                ],
                [new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text)]),
            [NodeKind.EmissiveTexture] = new(
                NodeKind.EmissiveTexture,
                Title(NodeKind.EmissiveTexture),
                Description(NodeKind.EmissiveTexture),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePinDefinition("Color", "Color", GraphValueType.Float4),
                    new NodePinDefinition("RGB", "RGB", GraphValueType.Float3),
                    new NodePinDefinition("R", "R", GraphValueType.Float1),
                    new NodePinDefinition("G", "G", GraphValueType.Float1),
                    new NodePinDefinition("B", "B", GraphValueType.Float1),
                    new NodePinDefinition("A", "A", GraphValueType.Float1),
                    new NodePinDefinition("Mask", "Mask", GraphValueType.Float1),
                ],
                [
                    new NodePropertyDefinition("ResourceName", "ResourceName", "emissive.png", NodePropertyKind.Text),
                    new NodePropertyDefinition("SourcePath", "SourcePath", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TextureMode", "TextureMode", "Static", NodePropertyKind.Text),
                    new NodePropertyDefinition("AddressMode", "AddressMode", "Wrap", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("ColorSpace", "ColorSpace", "Color", NodePropertyKind.Text),
                    new NodePropertyDefinition("MaskChannel", "MaskChannel", "A", NodePropertyKind.Text),
                ]),
            [NodeKind.NormalMap] = new(
                NodeKind.NormalMap,
                Title(NodeKind.NormalMap),
                Description(NodeKind.NormalMap),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Normal", "Normal", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("ResourceName", "ResourceName", "normal.png", NodePropertyKind.Text),
                    new NodePropertyDefinition("SourcePath", "SourcePath", string.Empty, NodePropertyKind.Text),
                    new NodePropertyDefinition("TextureMode", "TextureMode", "Static", NodePropertyKind.Text),
                    new NodePropertyDefinition("AddressMode", "AddressMode", "Wrap", NodePropertyKind.Text),
                    new NodePropertyDefinition("FilterMode", "FilterMode", "Linear", NodePropertyKind.Text),
                    new NodePropertyDefinition("Strength", "Strength", "1.0"),
                    new NodePropertyDefinition("XChannel", "XChannel", "R", NodePropertyKind.Text),
                    new NodePropertyDefinition("YChannel", "YChannel", "G", NodePropertyKind.Text),
                    new NodePropertyDefinition("InvertY", "InvertY", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.DetailNormalBlend] = new(
                NodeKind.DetailNormalBlend,
                Title(NodeKind.DetailNormalBlend),
                Description(NodeKind.DetailNormalBlend),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("BaseNormal", "BaseNormal", GraphValueType.Float4),
                    new NodePinDefinition("DetailNormal", "DetailNormal", GraphValueType.Float4),
                    new NodePinDefinition("ReferenceNormal", "ReferenceNormal", GraphValueType.Float4),
                    new NodePinDefinition("Strength", "Strength", GraphValueType.Float1),
                ],
                [new NodePinDefinition("Normal", "Normal", GraphValueType.Float4)],
                [new NodePropertyDefinition("Strength", "Strength", "1.0")]),
            [NodeKind.ParallaxUv] = new(
                NodeKind.ParallaxUv,
                Title(NodeKind.ParallaxUv),
                Description(NodeKind.ParallaxUv),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("Height", "Height", GraphValueType.Float1),
                    new NodePinDefinition("ViewDir", "ViewDir", GraphValueType.Float4),
                ],
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [
                    new NodePropertyDefinition("Scale", "Scale", "0.05"),
                    new NodePropertyDefinition("Center", "Center", "0.5"),
                ]),
            [NodeKind.ApplyTextureValue] = new(
                NodeKind.ApplyTextureValue,
                Title(NodeKind.ApplyTextureValue),
                Description(NodeKind.ApplyTextureValue),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ApplySphereAdd] = new(
                NodeKind.ApplySphereAdd,
                Title(NodeKind.ApplySphereAdd),
                Description(NodeKind.ApplySphereAdd),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("Base", "Base", GraphValueType.Float4),
                    new NodePinDefinition("Sphere", "Sphere", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ApplySphereMul] = new(
                NodeKind.ApplySphereMul,
                Title(NodeKind.ApplySphereMul),
                Description(NodeKind.ApplySphereMul),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [
                    new NodePinDefinition("Base", "Base", GraphValueType.Float4),
                    new NodePinDefinition("Sphere", "Sphere", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ApplySphereReplace] = new(
                NodeKind.ApplySphereReplace,
                Title(NodeKind.ApplySphereReplace),
                Description(NodeKind.ApplySphereReplace),
                NodeCategory.Texture,
                Color.FromArgb(78, 138, 86),
                [new NodePinDefinition("Sphere", "Sphere", GraphValueType.Float4)],
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
        })
        {
            definitions[pair.Key] = pair.Value;
        }
    }
}
