using System.Drawing;
using System.Text.RegularExpressions;

namespace RayMmdNodeEditor.Graph;

public static partial class NodeRegistry
{
    private static readonly IReadOnlyDictionary<NodeKind, NodeDefinition> Definitions = BuildDefinitions();
    private static readonly HashSet<NodeKind> HiddenKinds =
    [
        NodeKind.PrincipledPBR,
        NodeKind.MixMaterial,
    ];

    private static IReadOnlyDictionary<NodeKind, NodeDefinition> BuildDefinitions()
    {
        var definitions = new Dictionary<NodeKind, NodeDefinition>();
        AddInputGeometryDefinitions(definitions);
        AddTextureDefinitions(definitions);
        AddShadingSceneDefinitions(definitions);
        AddMathDefinitions(definitions);
        AddControlOutputDefinitions(definitions);
        AddRayDefinitions(definitions);
        return definitions;
    }

    public static IEnumerable<NodeDefinition> All => Definitions.Values.Where(definition => !HiddenKinds.Contains(definition.Kind));

    public static NodeDefinition Get(NodeKind kind) => Definitions[kind];

    private static string Title(NodeKind kind)
    {
        return kind switch
        {
            NodeKind.Scalar => "数值 Float1",
            NodeKind.Float2Value => "Float2",
            NodeKind.Float3Value => "Float3",
            NodeKind.Float4Value => "Float4",
            NodeKind.Color => "颜色",
            NodeKind.Add => "加法",
            NodeKind.Subtract => "减法",
            NodeKind.Multiply => "乘法",
            NodeKind.Divide => "除法",
            NodeKind.Min => "最小值",
            NodeKind.Max => "最大值",
            NodeKind.Abs => "绝对值",
            NodeKind.Sign => "符号",
            NodeKind.Power => "幂运算",
            NodeKind.Floor => "向下取整",
            NodeKind.Frac => "小数部分",
            NodeKind.Ceil => "向上取整",
            NodeKind.Truncate => "截断取整",
            NodeKind.Round => "四舍五入",
            NodeKind.Modulo => "取模",
            NodeKind.Sine => "正弦",
            NodeKind.Cosine => "余弦",
            NodeKind.Tangent => "正切",
            NodeKind.ArcSine => "反正弦",
            NodeKind.ArcCosine => "反余弦",
            NodeKind.ArcTangent => "反正切",
            NodeKind.ToRadians => "转弧度",
            NodeKind.ToDegrees => "转角度",
            NodeKind.SquareRoot => "平方根",
            NodeKind.ReciprocalSquareRoot => "倒数平方根",
            NodeKind.Logarithm => "自然对数",
            NodeKind.Exponent => "自然指数",
            NodeKind.Normalize => "归一化",
            NodeKind.Dot => "点积",
            NodeKind.Cross => "叉积",
            NodeKind.Length => "长度",
            NodeKind.Distance => "距离",
            NodeKind.Project => "投影",
            NodeKind.Clamp => "限制范围",
            NodeKind.Step => "阶跃",
            NodeKind.SmoothStep => "平滑阶跃",
            NodeKind.LessThan => "小于",
            NodeKind.GreaterThan => "大于",
            NodeKind.LessEqual => "小于等于",
            NodeKind.GreaterEqual => "大于等于",
            NodeKind.Equal => "等于",
            NodeKind.NotEqual => "不等于",
            NodeKind.Saturate => "饱和",
            NodeKind.Remap => "范围重映射",
            NodeKind.Lerp => "线性插值",
            NodeKind.OneMinus => "反相 1-X",
            NodeKind.SplitColor => "拆分颜色",
            NodeKind.SplitXY => "拆分 XY",
            NodeKind.SplitXYZ => "拆分 XYZ",
            NodeKind.SplitXYZW => "拆分 XYZW",
            NodeKind.ComposeColor => "合成颜色",
            NodeKind.AppendFloat2 => "合成 Float2",
            NodeKind.MergeXYZ => "合成 XYZ",
            NodeKind.MergeXYZW => "合成 XYZW",
            NodeKind.ComponentMask => "通道遮罩",
            NodeKind.ColorRamp => "颜色渐变",
            NodeKind.RgbCurve => "RGB 曲线",
            NodeKind.ColorAdjust => "颜色调整",
            NodeKind.LayerBlend => "图层混合",
            NodeKind.GradientTexture => "渐变纹理",
            NodeKind.CheckerTexture => "棋盘纹理",
            NodeKind.WaveTexture => "波纹纹理",
            NodeKind.UvTransform => "UV 缩放偏移",
            NodeKind.Panner => "UV 滚动",
            NodeKind.Time => "时间",
            NodeKind.Reroute => "转接点",
            NodeKind.Frame => "分组框",
            NodeKind.TexCoord => "UV Channel",
            NodeKind.SubTextureUv => "Sub UV",
            NodeKind.VertexChannel => "Vertex Channel",
            NodeKind.ScreenUv => "Screen UV",
            NodeKind.SceneViewRay => "Scene View Ray",
            NodeKind.MatCapUv => "MatCap UV",
            NodeKind.MaterialTexture => "Material Texture",
            NodeKind.TriplanarBoxmap => "Triplanar / Boxmap",
            NodeKind.Wetness => "Wetness",
            NodeKind.MaterialOutput => "Material Output",
            NodeKind.FresnelSchlick => "Fresnel Schlick",
            NodeKind.GGXSpecular => "GGX Specular",
            NodeKind.BurleyDiffuse => "Burley Diffuse",
            NodeKind.BRDFLighting => "BRDF Lighting",
            NodeKind.SmithJointGGX => "Smith Joint GGX",
            NodeKind.CookTorranceSpecular => "Cook Torrance Specular",
            NodeKind.PreIntegratedFGD => "PreIntegrated FGD",
            NodeKind.AnisotropicGGXSpecular => "Anisotropic GGX Specular",
            NodeKind.KelemenSzirmayKalosSpecular => "Kelemen Szirmay-Kalos Specular",
            NodeKind.DisneyPrincipledLite => "Disney Principled Lite",
            NodeKind.DisneyPrincipled => "Disney Principled",
            NodeKind.PrincipledPBR => "Principled PBR",
            NodeKind.MixMaterial => "Mix Material",
            NodeKind.NoiseTexture => "Noise Texture",
            NodeKind.VoronoiTexture => "Voronoi",
            NodeKind.FbmNoise => "FBM",
            NodeKind.DomainWarp => "Domain Warp",
            NodeKind.MusgraveTexture => "Musgrave",
            NodeKind.CellEdgeTexture => "Cell Edge",
            NodeKind.CurlNoise => "Curl Noise",
            NodeKind.AnisotropicNoise => "Anisotropic Noise",
            NodeKind.BrickTexture => "Brick Texture",
            NodeKind.MaterialSphereMap => "Material Sphere Map",
            NodeKind.MaterialToonTexture => "Material Toon Texture",
            NodeKind.EmissiveTexture => "Emissive Texture",
            NodeKind.NormalMap => "Normal Map",
            NodeKind.SharedParameter => "Shared Parameter",
            NodeKind.SurfaceTangent => "Surface Tangent",
            NodeKind.SurfaceBitangent => "Surface Bitangent",
            NodeKind.HairTangent => "Hair Tangent",
            NodeKind.TransformPosition => "Transform Position",
            NodeKind.TransformVector => "Transform Vector",
            NodeKind.UvRotate => "UV 旋转",
            NodeKind.Sigmoid => "Sigmoid",
            NodeKind.Softmax => "Softmax",
            NodeKind.ToonRampSample => "Toon Ramp Sample",
            NodeKind.GenshinRamp => "Genshin Ramp",
            NodeKind.SnowBreakRamp => "SnowBreak Ramp",
            NodeKind.GenericRampSample => "Generic Ramp",
            NodeKind.SkinPreintegratedLut => "Skin Preintegrated LUT",
            NodeKind.RimShadow => "Rim Shadow",
            NodeKind.ShadowRampColor => "Lighting Ramp",
            NodeKind.MatCapBlendMode => "MatCap Blend Mode",
            NodeKind.SceneColor => "Scene Color",
            NodeKind.SceneDepth => "Scene Depth",
            NodeKind.LayerSource => "Layer Source",
            NodeKind.OffscreenBufferSample => "Offscreen Buffer Sample",
            NodeKind.SharedTextureSample => "Shared Texture Sample",
            NodeKind.DiffuseEnvSample => "Diffuse Env Sample",
            NodeKind.SpecularEnvSample => "Specular Env Sample",
            NodeKind.DiffuseEnvBake => "Diffuse Env Bake",
            NodeKind.SpecularEnvBake => "Specular Env Bake",
            NodeKind.EnvironmentLightingPBR => "Environment Lighting PBR",
            NodeKind.PackPipelineSurface => "Pack Pipeline Surface",
            NodeKind.PipelineEnvironmentLighting => "Pipeline Environment Lighting",
            NodeKind.ParallaxUv => "Parallax UV",
            NodeKind.DirectionToLatLongUv => "Direction To LatLong UV",
            NodeKind.DepthVisualize => "Depth Visualize",
            NodeKind.ScreenUvOffset => "Screen UV Offset",
            NodeKind.BufferCompare => "Buffer Compare",
            NodeKind.DepthEdgeDetect => "Depth Edge Detect",
            NodeKind.NormalEdgeDetect => "Normal Edge Detect",
            NodeKind.MaskBufferDebug => "Mask Buffer Debug",
            NodeKind.ScreenSpaceRimCompose => "Screen Space Rim Compose",
            NodeKind.BrightExtract => "Bright Extract",
            NodeKind.GaussianBlur => "Gaussian Blur",
            NodeKind.SceneNormalSample => "Scene Normal Sample",
            NodeKind.ViewPositionFromDepth => "View Position From Depth",
            NodeKind.BilateralBlur => "Bilateral Blur",
            NodeKind.Downsample => "Downsample",
            NodeKind.UpsampleBlend => "Upsample Blend",
            NodeKind.Group => "Group",
            NodeKind.GroupInput => "Group Input",
            NodeKind.GroupOutput => "Group Output",
            NodeKind.TextureCoordinate => "Texture Coordinate",
            NodeKind.CameraData => "Camera Data",
            NodeKind.FakeEnvReflection => "Fake Env Reflection",
            NodeKind.MatCapAtlasSample => "MatCap Atlas Sample",
            NodeKind.RayTextureSlot => "Ray 贴图槽",
            NodeKind.RayMaterialOutput => "Ray 材质输出",
            NodeKind.RayEmissivePulse => "Ray 自发光脉冲",
            NodeKind.RayLightDirection => "Ray 灯光方向",
            NodeKind.RayLightingMix => "Ray 光照混合",
            NodeKind.RayNormalStrength => "Ray 法线强度",
            NodeKind.RayCustomData => "Ray Custom 数据",
            NodeKind.RayReflectionBridge => "Ray 反射桥",
            NodeKind.RayClearCoatBridge => "Ray ClearCoat 桥",
            NodeKind.RayAnisotropyBridge => "Ray 各向异性桥",
            NodeKind.RayClothBridge => "Ray 布料桥",
            NodeKind.RaySkinSssBridge => "Ray 皮肤 SSS 桥",
            NodeKind.RayToonCelBridge => "Ray Toon/Cel 桥",
            NodeKind.RayBrdfToRayBridge => "Ray BRDF -> Ray",
            NodeKind.RayShadingOutput => "Ray 最终着色输出",
            NodeKind.RaySceneColor => "Ray Scene Color",
            NodeKind.RaySceneDepth => "Ray Scene Depth",
            NodeKind.RaySceneNormal => "Ray Scene Normal",
            NodeKind.RaySsao => "Ray SSAO/SSDO",
            NodeKind.RayMultiLight => "Ray Multi Light",
            NodeKind.RayAccumulatedLighting => "Ray 累积光照",
            NodeKind.RaySunLightData => "Ray Sun Light Data",
            NodeKind.RayDebugView => "Ray 通道调试",
            NodeKind.RayIblReflection => "Ray IBL / 反射",
            NodeKind.RayShadowData => "Ray Shadow",
            NodeKind.RaySkinAdvanced => "Ray Skin SSS",
            NodeKind.RaySnowLayer => "Ray 雪层",
            NodeKind.RayDustLayer => "Ray 尘土层",
            NodeKind.RayEdgeWear => "Ray 边缘磨损",
            NodeKind.RayMaterialLayer => "Ray 材质分层",
            NodeKind.RaySsrReflection => "Ray SSR 反射",
            NodeKind.RayOutlineChannel => "Ray Outline 通道",
            NodeKind.RayFogChannel => "Ray Fog / Godray",
            NodeKind.RayIblSplit => "Ray IBL 分离",
            NodeKind.RayChannelSplit => "Ray 通道拆分",
            NodeKind.RayMaterialDiagnostic => "Ray 材质诊断",
            NodeKind.RayFogDepthBlend => "Ray Fog Depth Blend",
            NodeKind.RayControllerInput => "Ray 控制器输入",
            NodeKind.RayPostParameter => "Ray 后期参数",
            NodeKind.RayDebugController => "Ray Debug Controller",
            NodeKind.LayerSourceOutput => "Layer Source Output",
            NodeKind.RimDepthBuffer => "Rim Depth Buffer",
            NodeKind.RimMaskBuffer => "Mask Buffer",
            NodeKind.HalfLambert => "Half Lambert",
            NodeKind.BlinnPhong => "Blinn Phong",
            NodeKind.WrapLighting => "Wrap Lighting",
            NodeKind.GouraudLighting => "Gouraud Lighting",
            NodeKind.OrenNayarLighting => "Oren-Nayar Lighting",
            NodeKind.OrenNayarDiffuseReflection => "Oren-Nayar Diffuse",
            NodeKind.OrenNayarBlinn => "Oren-Nayar Blinn",
            NodeKind.MinnaertLighting => "Minnaert Lighting",
            NodeKind.KajiyaKay => "Kajiya-Kay",
            NodeKind.Bssrdf => "BSSRDF",
            NodeKind.SubsurfaceScattering => "Subsurface Scattering",
            NodeKind.TonemapLite => "Tonemap Lite",
            NodeKind.FaceSdfSample => "Face SDF Sample",
            NodeKind.FaceSdfShadow => "Face SDF Shadow",
            NodeKind.OffsetAlongNormal => "Offset Along Normal",
            NodeKind.VertexWave => "Vertex Wave",
            NodeKind.AxisMask => "Axis Mask",
            NodeKind.Twist => "Twist",
            NodeKind.Bend => "Bend",
            NodeKind.NoiseDisplace => "Noise Displace",
            NodeKind.NdotL => "NdotL",
            NodeKind.NdotV => "NdotV",
            NodeKind.NdotH => "NdotH",
            NodeKind.PointLightAttenuation => "Point Light Attenuation",
            NodeKind.VirtualLight => "Virtual Light",
            NodeKind.VirtualDirectionalShadowMask => "Virtual Directional Shadow Mask",
            NodeKind.VirtualDirectionalShadowLight => "Virtual Directional Shadow Light",
            NodeKind.VirtualDirectionalShadowDual => "Virtual Directional Shadow Dual",
            NodeKind.SelfShadowLighting => "Self Shadow Lighting",
            _ => Regex.Replace(kind.ToString(), "([a-z0-9])([A-Z])", "$1 $2"),
        };
    }

    private static string Description(NodeKind kind)
    {
        return $"用于 {Title(kind)} 的节点。";
    }
}
