using System.Drawing;

namespace RayMmdNodeEditor.Graph;

public static partial class NodeRegistry
{
    private static void AddInputGeometryDefinitions(Dictionary<NodeKind, NodeDefinition> definitions)
    {
        foreach (var pair in new Dictionary<NodeKind, NodeDefinition>
        {
            [NodeKind.Scalar] = new(
                NodeKind.Scalar,
                Title(NodeKind.Scalar),
                Description(NodeKind.Scalar),
                NodeCategory.Input,
                Color.FromArgb(140, 122, 190),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                [new NodePropertyDefinition("Value", "Value", "1.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f)]),
            [NodeKind.Float2Value] = new(
                NodeKind.Float2Value,
                Title(NodeKind.Float2Value),
                Description(NodeKind.Float2Value),
                NodeCategory.Input,
                Color.FromArgb(91, 168, 255),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float2)],
                [
                    new NodePropertyDefinition("X", "X", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                    new NodePropertyDefinition("Y", "Y", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                ]),
            [NodeKind.Float3Value] = new(
                NodeKind.Float3Value,
                Title(NodeKind.Float3Value),
                Description(NodeKind.Float3Value),
                NodeCategory.Input,
                Color.FromArgb(88, 208, 174),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float3)],
                [
                    new NodePropertyDefinition("X", "X", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                    new NodePropertyDefinition("Y", "Y", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                    new NodePropertyDefinition("Z", "Z", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                ]),
            [NodeKind.Float4Value] = new(
                NodeKind.Float4Value,
                Title(NodeKind.Float4Value),
                Description(NodeKind.Float4Value),
                NodeCategory.Input,
                Color.FromArgb(245, 164, 84),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("X", "X", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                    new NodePropertyDefinition("Y", "Y", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                    new NodePropertyDefinition("Z", "Z", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                    new NodePropertyDefinition("W", "W", "0.0", Editor: NodePropertyEditorKind.Numeric, AllowInlineEditor: true, Minimum: -10f, Maximum: 10f, Step: 0.01f),
                ]),
            [NodeKind.Color] = new(
                NodeKind.Color,
                Title(NodeKind.Color),
                Description(NodeKind.Color),
                NodeCategory.Input,
                Color.FromArgb(198, 112, 74),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Color", "Color", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("R", "R", "1.0", Editor: NodePropertyEditorKind.Color, AllowInlineEditor: true, Minimum: 0f, Maximum: 1f, Step: 0.01f),
                    new NodePropertyDefinition("G", "G", "1.0", Editor: NodePropertyEditorKind.Color, AllowInlineEditor: true, Minimum: 0f, Maximum: 1f, Step: 0.01f),
                    new NodePropertyDefinition("B", "B", "1.0", Editor: NodePropertyEditorKind.Color, AllowInlineEditor: true, Minimum: 0f, Maximum: 1f, Step: 0.01f),
                    new NodePropertyDefinition("A", "A", "1.0", Editor: NodePropertyEditorKind.Color, AllowInlineEditor: true, Minimum: 0f, Maximum: 1f, Step: 0.01f),
                ]),
            [NodeKind.Time] = new(
                NodeKind.Time,
                Title(NodeKind.Time),
                Description(NodeKind.Time),
                NodeCategory.Input,
                Color.FromArgb(140, 122, 190),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.UseSubTextureFlag] = new(
                NodeKind.UseSubTextureFlag,
                Title(NodeKind.UseSubTextureFlag),
                Description(NodeKind.UseSubTextureFlag),
                NodeCategory.Input,
                Color.FromArgb(140, 122, 190),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ElapsedTime] = new(
                NodeKind.ElapsedTime,
                Title(NodeKind.ElapsedTime),
                Description(NodeKind.ElapsedTime),
                NodeCategory.Input,
                Color.FromArgb(140, 122, 190),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ViewportPixelSize] = new(
                NodeKind.ViewportPixelSize,
                Title(NodeKind.ViewportPixelSize),
                Description(NodeKind.ViewportPixelSize),
                NodeCategory.Input,
                Color.FromArgb(140, 122, 190),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("Value", "Value", GraphValueType.Float2),
                    new NodePinDefinition("X", "X", GraphValueType.Float1),
                    new NodePinDefinition("Y", "Y", GraphValueType.Float1),
                ],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.TexCoord] = new(
                NodeKind.TexCoord,
                Title(NodeKind.TexCoord),
                Description(NodeKind.TexCoord),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                [new NodePropertyDefinition("Source", "Source", "MainUV", NodePropertyKind.Text)]),
            [NodeKind.TextureCoordinate] = new(
                NodeKind.TextureCoordinate,
                Title(NodeKind.TextureCoordinate),
                Description(NodeKind.TextureCoordinate),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("Object", "Object", GraphValueType.Float4),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("Camera", "Camera", GraphValueType.Float4),
                    new NodePinDefinition("Window", "Window", GraphValueType.Float2),
                    new NodePinDefinition("Reflection", "Reflection", GraphValueType.Float4),
                ],
                [new NodePropertyDefinition("Source", "UV Source", "MainUV", NodePropertyKind.Text)]),
            [NodeKind.SubTextureUv] = new(
                NodeKind.SubTextureUv,
                Title(NodeKind.SubTextureUv),
                Description(NodeKind.SubTextureUv),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.VertexChannel] = new(
                NodeKind.VertexChannel,
                Title(NodeKind.VertexChannel),
                Description(NodeKind.VertexChannel),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [new NodePropertyDefinition("Source", "Source", "MainUV", NodePropertyKind.Text)]),
            [NodeKind.LocalPosition] = new(
                NodeKind.LocalPosition,
                Title(NodeKind.LocalPosition),
                Description(NodeKind.LocalPosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.LocalNormal] = new(
                NodeKind.LocalNormal,
                Title(NodeKind.LocalNormal),
                Description(NodeKind.LocalNormal),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.WorldPosition] = new(
                NodeKind.WorldPosition,
                Title(NodeKind.WorldPosition),
                Description(NodeKind.WorldPosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ClipSpacePosition] = new(
                NodeKind.ClipSpacePosition,
                Title(NodeKind.ClipSpacePosition),
                Description(NodeKind.ClipSpacePosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.WorldNormal] = new(
                NodeKind.WorldNormal,
                Title(NodeKind.WorldNormal),
                Description(NodeKind.WorldNormal),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SurfaceTangent] = new(
                NodeKind.SurfaceTangent,
                Title(NodeKind.SurfaceTangent),
                Description(NodeKind.SurfaceTangent),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("WorldPos", "WorldPos", GraphValueType.Float4),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Tangent", "Tangent", GraphValueType.Float4)],
                [new NodePropertyDefinition("Source", "Source", "MainUV", NodePropertyKind.Text)]),
            [NodeKind.SurfaceBitangent] = new(
                NodeKind.SurfaceBitangent,
                Title(NodeKind.SurfaceBitangent),
                Description(NodeKind.SurfaceBitangent),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("WorldPos", "WorldPos", GraphValueType.Float4),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("Tangent", "Tangent", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Bitangent", "Bitangent", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Source", "Source", "MainUV", NodePropertyKind.Text),
                    new NodePropertyDefinition("Invert", "Flip", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.HairTangent] = new(
                NodeKind.HairTangent,
                Title(NodeKind.HairTangent),
                Description(NodeKind.HairTangent),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("UV", "UV", GraphValueType.Float2),
                    new NodePinDefinition("WorldPos", "WorldPos", GraphValueType.Float4),
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("Source", "Source", "MainUV", NodePropertyKind.Text),
                    new NodePropertyDefinition("StrandAxis", "Strand Axis", "V", NodePropertyKind.Text),
                    new NodePropertyDefinition("Invert", "Flip", "False", NodePropertyKind.Text),
                ]),
            [NodeKind.ViewDirection] = new(
                NodeKind.ViewDirection,
                Title(NodeKind.ViewDirection),
                Description(NodeKind.ViewDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.CameraPosition] = new(
                NodeKind.CameraPosition,
                Title(NodeKind.CameraPosition),
                Description(NodeKind.CameraPosition),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.CameraData] = new(
                NodeKind.CameraData,
                Title(NodeKind.CameraData),
                Description(NodeKind.CameraData),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [
                    new NodePinDefinition("ViewVector", "ViewVector", GraphValueType.Float4),
                    new NodePinDefinition("Distance", "Distance", GraphValueType.Float1),
                ],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.LightDirection] = new(
                NodeKind.LightDirection,
                Title(NodeKind.LightDirection),
                Description(NodeKind.LightDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.HalfVector] = new(
                NodeKind.HalfVector,
                Title(NodeKind.HalfVector),
                Description(NodeKind.HalfVector),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("ViewDir", "ViewDir", GraphValueType.Float4),
                    new NodePinDefinition("LightDir", "LightDir", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.EulerToDirection] = new(
                NodeKind.EulerToDirection,
                Title(NodeKind.EulerToDirection),
                Description(NodeKind.EulerToDirection),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [new NodePinDefinition("Rotation", "Rotation", GraphValueType.Float4)],
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                [
                    new NodePropertyDefinition("BaseX", "BaseX", "0.0"),
                    new NodePropertyDefinition("BaseY", "BaseY", "0.0"),
                    new NodePropertyDefinition("BaseZ", "BaseZ", "1.0"),
                ]),
            [NodeKind.NdotL] = new(
                NodeKind.NdotL,
                Title(NodeKind.NdotL),
                Description(NodeKind.NdotL),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("LightDir", "LightDir", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.NdotV] = new(
                NodeKind.NdotV,
                Title(NodeKind.NdotV),
                Description(NodeKind.NdotV),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("ViewDir", "ViewDir", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.NdotH] = new(
                NodeKind.NdotH,
                Title(NodeKind.NdotH),
                Description(NodeKind.NdotH),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                [
                    new NodePinDefinition("Normal", "Normal", GraphValueType.Float4),
                    new NodePinDefinition("Half", "Half", GraphValueType.Float4),
                ],
                [new NodePinDefinition("Result", "Result", GraphValueType.Float1)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.ScreenUv] = new(
                NodeKind.ScreenUv,
                Title(NodeKind.ScreenUv),
                Description(NodeKind.ScreenUv),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.SceneViewRay] = new(
                NodeKind.SceneViewRay,
                Title(NodeKind.SceneViewRay),
                Description(NodeKind.SceneViewRay),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MatCapUv] = new(
                NodeKind.MatCapUv,
                Title(NodeKind.MatCapUv),
                Description(NodeKind.MatCapUv),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("UV", "UV", GraphValueType.Float2)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MaterialDiffuse] = new(
                NodeKind.MaterialDiffuse,
                Title(NodeKind.MaterialDiffuse),
                Description(NodeKind.MaterialDiffuse),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MaterialAmbient] = new(
                NodeKind.MaterialAmbient,
                Title(NodeKind.MaterialAmbient),
                Description(NodeKind.MaterialAmbient),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MaterialEmissive] = new(
                NodeKind.MaterialEmissive,
                Title(NodeKind.MaterialEmissive),
                Description(NodeKind.MaterialEmissive),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MaterialSpecularColor] = new(
                NodeKind.MaterialSpecularColor,
                Title(NodeKind.MaterialSpecularColor),
                Description(NodeKind.MaterialSpecularColor),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.MaterialToonColor] = new(
                NodeKind.MaterialToonColor,
                Title(NodeKind.MaterialToonColor),
                Description(NodeKind.MaterialToonColor),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.LightDiffuse] = new(
                NodeKind.LightDiffuse,
                Title(NodeKind.LightDiffuse),
                Description(NodeKind.LightDiffuse),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.LightAmbient] = new(
                NodeKind.LightAmbient,
                Title(NodeKind.LightAmbient),
                Description(NodeKind.LightAmbient),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.EdgeColorNode] = new(
                NodeKind.EdgeColorNode,
                Title(NodeKind.EdgeColorNode),
                Description(NodeKind.EdgeColorNode),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
            [NodeKind.GroundShadowColorNode] = new(
                NodeKind.GroundShadowColorNode,
                Title(NodeKind.GroundShadowColorNode),
                Description(NodeKind.GroundShadowColorNode),
                NodeCategory.Geometry,
                Color.FromArgb(84, 124, 184),
                Array.Empty<NodePinDefinition>(),
                [new NodePinDefinition("Value", "Value", GraphValueType.Float4)],
                Array.Empty<NodePropertyDefinition>()),
        })
        {
            definitions[pair.Key] = pair.Value;
        }
    }
}
